In [2]:
print("hello world")

hello world


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
""" 
 Veri Biliminin Temel Adımları:

- Veri toplama : doğru şekilde verilerin toplaması
- Veri temizleme : aykırı değerlerin temizlenmesi, hataların-boşların temizlenmesi
- Veri Keşif ve Görselleştirme : keşifsel analizler ve görselleştirme teknikleri kullanılır. Bu adım, verinin özelliklerini anlamaya, olası sorunları tespit etmeye ve hangi analiz yöntemlerinin uygun olacağına karar vermeye yardımcı olur
- Veri Modelleme : hangi yapay zeka aracı kullanılacak tahminleme, sınfılama. Desenler patternler ortaya çıkarılır
- Model Değerlendirme : Modeli test et, modelin %80 modelin train edilmesi %20 test edilmesi
- Sonuçların sunumu ve yorumlanması  
"""

' \n Veri Biliminin Temel Adımları:\n\n- Veri toplama : doğru şekilde verilerin toplaması\n- Veri temizleme : aykırı değerlerin temizlenmesi, hataların-boşların temizlenmesi\n- Veri Keşif ve Görselleştirme : keşifsel analizler ve görselleştirme teknikleri kullanılır. Bu adım, verinin özelliklerini anlamaya, olası sorunları tespit etmeye ve hangi analiz yöntemlerinin uygun olacağına karar vermeye yardımcı olur\n- Veri Modelleme : hangi yapay zeka aracı kullanılacak tahminleme, sınfılama. Desenler patternler ortaya çıkarılır\n- Model Değerlendirme : Modeli test et, modelin %80 modelin train edilmesi %20 test edilmesi\n- Sonuçların sunumu ve yorumlanması  \n'

In [5]:
liste_2d = [[1,2,3],[4,5,6],[7,8,9]]
nump_array_2d = np.array(liste_2d)
nump_array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
zeros_array = np.zeros((5,6))
ones_array = np.ones((3,2))
zeros_array
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
range_array = np.arange(1,11)
range_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
zeros_array.shape # (5,6) = (row,column)
zeros_array.ndim # 2  = (n dimension)
zeros_array.size # 30  = how many item
zeros_array.dtype # float64 = type of data in matrix

dtype('float64')

In [9]:
print(zeros_array[0][2]) # matrixin 0. satırının 2. sütünüdaki değer 
print("------------")

print(zeros_array[0:3])
print("------------")

print(zeros_array[:3])
print("------------")
print(zeros_array[3:])

0.0
------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [10]:
nump_array_2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(nump_array_2d[1:3, 0:2]) # 1 nci satırdan 3 ncü satıra kadar(dahil) KESİŞİM 0 ncı sütündan 2 nci sütuna kadar(dahil)
print("--------------")

[[4 5]
 [7 8]]
--------------


In [12]:
print(nump_array_2d[:,1:])

[[2 3]
 [5 6]
 [8 9]]


In [ ]:
from numpy import random
rand_array = random.randint(100, size=(3, 5)) # 0-100 arasında random sayılarla 3X5 lik bir matriks oluşturma
print(rand_array)

[[54 95 13 66 10]
 [82 37 25 24 67]
 [62  2 28 11 10]]


In [14]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)     # addition
print(array1 - array2)     # subtraction
print(array1 * array2)     # multiplication
print(array1 / array2)     # division
print(array1 ** 2)         # exponentiation


array = np.array([1, 2, 3, 4, 5])
print(np.sum(array))     # total
print(np.mean(array))     # mean
print(np.median(array))   # median
print(np.std(array))     # standard deviation
print(np.max(array))
print(np.min(array))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
15
3.0
3.0
1.4142135623730951
5
1


In [ ]:
ar1 = np.array([[1,2,3],[4,5,6]])  # 2X3 ; 2 satır, 3 sütun

ar2 = np.array([[1,2],[3,4],[5,6]])  #3X2 ; 3 satır, 2 sütun

result = np.dot(ar1,ar2) # matriks çarpımı yapabilme koşulu : iki matriks çarpılabilmesi için ilkinin sütun sayısı eşit olmalı 2nci matrisin satır sayısına

result 
"""
array([[22, 28],
       [49, 64]])
"""
 # yeni oluşan matriksin boyutu 1 ncisinin satır sayısı, 2 ncisinin sütun sayısı kadar olmalı

array([[22, 28],
       [49, 64]])